### ISSUE TITLE
Windows .ico

### ISSUE THREAD

**Issue by vico93** [wader/inkmake#5]
Can it be used to create multi-size Windows Icons? I currently use imagemagick + inkscape via command line but its pretty slow and doesnt give me best quality.

**Comment by wader** [comment]
Hi! There is no support for ico directly in inkmake unfortunately, it rely on inkscape for exporting. But in what way is the quality bad? Is it because ImageMagick/GraphicsMagick does the resizing using a raster image?

After some googling maybe a combination of inkmake and a script could be a solution for you. Something like:

`Inkfile`:
```
icon[16=16x16|32=32x32|48=48x48|128=128x128|256=256x256].png
```
`make-ico.sh`:
```
convert icon16.png icon32.png icon48.png icon128.png icon256.png -colors 256 icon.ico
```
And then run both in sequence `inkmake && sh make-ico.sh` when you want to export to ico.

Hope that gives some inspiration!

**Comment by vico93** [comment]
One of the problems i have is, according to Windows guidelines, the small-sized images (16x16) should use 8-bit depth, and i dont know how to export a png with such parameter using inkscape.

Anyway thanks for the help!

**Comment by wader** [comment]
Aha ok! maybe do some preprocessing with imagemagick before merging to a ico?
